@courseId = 65b88a635617bc051f5daf66
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRAdGVzdC50ZXN0IiwidXNlcklkIjoiNjViYjNmNTRhY2I2MmQ5OGJkMGM0MThkIiwiaWF0IjoxNzA2Nzk4MjAyLCJleHAiOjE3MDY4MDE4MDJ9.Z6YdLE_PXutMGDQAyonGnF5FAUqjgObdxDIm-2Gp688

POST http://localhost:8080/courses/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
"name":"cousreName",
"instructorName":"instructorName",
"maxStudents":212,
"price":19.99
}
###

PUT http://localhost:8080/courses/{{courseId}}
Content-Type: application/json

{
"name":"2ndCousreName",
"instructor":"newInstructorName",
"maxStudents":212,
"price":19.55
}
###
DELETE http://localhost:8080/courses/{{courseId}}

