@courseId = 65c47e8f2905ee9e155a2459
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRAdGVzdC50ZXN0IiwidXNlcklkIjoiNjVjMWU3NjFkOTc2MTJhOWM2YTJjZGM3IiwiaWF0IjoxNzA4MDg0NjU4LCJleHAiOjE3MDgwODgyNTh9.y2W7xa2r9hUCC9raTuwdNkh_O84pVaMIquLqZTm6UyY

POST http://localhost:8080/courses/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
"name":"cousreNamesd12sdsd1",
"maxStudents":212,
"price":19.99
}
###

PUT http://localhost:8080/courses/{{courseId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
"name":"2ndCousreName",
"maxStudents":212,
"price":19.55
}
###
DELETE http://localhost:8080/courses/{{courseId}}
Authorization: Bearer {{token}}
###
POST http://localhost:8080/courses/{{courseId}}/subscribe
Content-Type: application/json
Authorization: Bearer {{token}}
###
DELETE http://localhost:8080/courses/{{courseId}}/unsubscribe
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET http://localhost:8080/courses
Authorization: Bearer {{token}}
###
GET http://localhost:8080/courses/{{courseId}}
Authorization: Bearer {{token}}
###
GET http://localhost:8080/courses/subscribed
Authorization: Bearer {{token}}
